test $TERM != "screen"; and exec tmux
alias runc='sh ~/bin/runc'
alias runcx='sh ~/bin/runcx'
alias runjava='sh ~/bin/runjava'
alias rmd='rm -rf $1/'
alias hello='sh ~/bin/hello'
alias hi='sh ~/bin/hello'
alias hii='sh ~/bin/hello'
alias take='sh ~/bin/take'
alias projects='cd ~/bin/codes/projects/'
alias ...='cd ../..'
alias ....='...;cd ../'
alias md='mkdir $1'
alias rd='rm -rf $1'

alias covidtracker='sh ~/bin/covidtracker'

alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gpl='git pull'
alias gst='git status'
alias gdf='git diff'
alias gl='git log'
